| `PageLayout_Navbar_Logout -> "Déconnexion"
| `PageLayout_Navbar_Network -> "Réseau"
| `PageLayout_Navbar_News -> "Actualités"
| `PageLayout_Navbar_Account -> "Mon Compte"
| `PageLayout_Navbar_Home -> "Accueil"
| `PageLayout_Navbar_Members -> "Membres"
| `PageLayout_Navbar_Events -> "Activités"
| `PageLayout_Navbar_Forums -> "Discussions"
| `PageLayout_Navbar_Website -> "Site Web"
| `PageLayout_Foot_PoweredBy -> "Propulsé par"
