| `PageLayout_Navbar_Logout -> "Déconnexion"
| `PageLayout_Navbar_Home -> "Messages"
| `PageLayout_Navbar_Members -> "Membres"
| `PageLayout_Navbar_Events -> "Agenda"
| `PageLayout_Navbar_Website -> "Site Web"
| `PageLayout_Navbar_Admin -> "Admin"
| `PageLayout_Navbar_Intranet -> "Espace Membres"
| `PageLayout_Navbar_Help -> "Support"
| `PageLayout_Navbar_NewHere -> "Un peu perdus ? Consultez l'aide en ligne." 
| `PageLayout_Foot_PoweredBy -> "Propulsé par"
| `PageLayout_Navbar_Public_Website -> "Accueil"
| `PageLayout_Navbar_Public_Calendar -> "Agenda"
| `PageLayout_Navbar_Public_About -> "À propos"
| `PageLayout_Navbar_Public_Join -> "Nous rejoindre"
| `PageLayout_Loading_Thanks -> "Veuillez patienter quelques instants..."
| `PageLayout_Picture_Edit -> "Changer de logo"
