| `Forums_Public -> "Forums Publics"
| `Forums_Public_Subtitle -> "Tous les membres de l'association peuvent voir et publier dans ces forums."
| `Forums_Public_Create -> "Créer un forum public"
| `Forums_Public_Empty -> "Aucun forum public"
| `Forums_Private -> "Forums Privés"
| `Forums_Private_Subtitle -> "Il faut être inscrit sur ces forums avant de pouvoir y participer."   
| `Forums_Private_Create -> "Créer un forum privé"
| `Forums_Private_Empty -> "Aucun forum privé"
| `Forums_OfGroup -> "Groupe"
| `Forums_NoMessage -> "Aucun message récent"

| `Forum_Section `Wall -> "Discussions"
| `Forum_Section `People -> "Inscrits"
| `Forum_Section `Album -> "Photos"
| `Forum_Section `Folder -> "Fichiers"
| `Forum_Admin -> "Administration"

| `Forum_Title_Group -> "Forum du groupe"
