| `Forums_Public -> "Forums Publics"
| `Forums_Public_Subtitle -> "Tous les membres de l'association peuvent voir et publier dans ces forums."
| `Forums_Public_Create -> "Créer un forum public"
| `Forums_Public_Empty -> "Aucun forum public"
| `Forums_Private -> "Forums Privés"
| `Forums_Private_Subtitle -> "Il faut être inscrit sur ces forums avant de pouvoir y participer."   
| `Forums_Private_Create -> "Créer un forum privé"
| `Forums_Private_Empty -> "Aucun forum privé"
| `Forums_Messages i -> if i = 1 then "message" else "messages"
| `Forums_Files i -> if i = 1 then "fichier" else "fichiers"
| `Forums_Pictures i -> if i = 1 then "photo" else "photos"
| `Forums_OfGroup -> "Forum du groupe"
