| `Login_Title
| `Login_Lost_Link
| `Login_Lost_Title
| `Login_Form_Reset_Submit
| `Login_Form_Reset_NotFound
| `Login_Form_Login
| `Login_Form_Password
| `Login_Form_Submit
| `Login_Form_Required
| `Login_Form_Error
| `Login_Form_Firstname
| `Login_Form_Lastname
| `Login_Form_Pass2
| `Login_Form_Signup_Submit
| `Login_Form_Signup_Mismatch
| `Login_Section_Login
| `Login_Section_Signup
| `Login_PopConfirmReset_Title
| `Login_PopConfirmReset_Intro
| `Login_PopConfirmReset_Outro
| `Login_PopReset_Intro
| `Login_PopReset_Outro
| `Login_ResetResend_Title
| `Login_ResetResend_Prelude
| `Login_ResetResend_Body 
| `Login_ResetResend_Sorry 
| `Login_RunOrg_Passport
| `Login_RunOrg_Passport_Info
