| `Login_Title -> "RunOrg - Connexion"
| `Login_Lost_Title -> "Récupérer un mot de passe"
| `Login_Lost_Link -> "Vous n'avez pas votre mot de passe ?"
| `Login_Form_Reset_Submit -> "Récupérer"
| `Login_Form_Reset_NotFound -> "Ce compte n'existe pas"
| `Login_Form_Login -> "Adresse email"
| `Login_Form_Password -> "Mot de passe"
| `Login_Form_Submit -> "Connexion"
| `Login_Form_Required -> "Champ obligatoire"
| `Login_Form_Error -> "Adresse ou mot de passe incorrect"
| `Login_Form_Firstname -> "Prénom"
| `Login_Form_Lastname -> "Nom"
| `Login_Form_Pass2 -> "Mot de passe (encore)"
| `Login_Form_Signup_Submit -> "Inscription"
| `Login_Form_Signup_Mismatch -> "Les mots de passe ne se correspondent pas"
| `Login_Section_Login -> "Vous avez déjà un compte ?"
| `Login_Section_Signup -> "Créer un nouveau compte"
| `Login_Heading_Core -> "Avec votre compte RunOrg gratuit, rejoignez ou créez des associations"
| `Login_Heading_Client -> "Pour accéder à cet espace, vous devez disposer d'un compte RunOrg"
| `Login_PopConfirmReset_Title -> "Mot de passe perdu" 
| `Login_PopConfirmReset_Intro  
| `Login_PopReset_Intro -> 
  "Nous vous avons envoyé un email à l'adresse"
| `Login_PopConfirmReset_Outro
| `Login_PopReset_Outro -> 
  "Cet email contient un lien qui vous permettra de vous connecter à votre compte et d'en changer le mot de passe."
| `Login_ResetResend_Title -> "Lien invalide"
| `Login_ResetResend_Prelude -> "Votre lien de changement de mot de passe n'est plus valable !"
| `Login_ResetResend_Body -> "Pour des raisons de sécurité, tous les liens de connexion ont une date limite de validité de trois jours. Au-delà, ils ne sont plus utilisables."
| `Login_ResetResend_Sorry -> "Nous vous avons envoyé un nouveau lien par mail."
