| `Start_Title -> "Créer une communauté - RunOrg"
| `Start_Heading -> "Créez votre communauté RunOrg !"
| `Start_Step_One -> "Choisissez le type de communauté"
| `Start_Step_Two -> "Complétez ses informations de profil"
| `Start_Field_Name -> "Le nom de votre communauté"
| `Start_Field_Key -> "L'adresse web pour y accéder"
| `Start_Add_Picture -> "Ajouter un logo ou une photo..."
| `Start_Field_Picture -> "Le logo ou la photo de l'espace" 
| `Start_Edit_Picture -> "Modifier"
| `Start_Add_Description -> "Ajouter une description..."
| `Start_Field_Description -> "Une courte description"
| `Start_Submit -> "Créer votre espace"
| `Start_Cancel -> "Annuler"
