| `JoinForm_Required -> "Obligatoire"
| `JoinForm_Kind_LongText -> "Texte"
| `JoinForm_Kind_Textarea -> "Texte long"
| `JoinForm_Kind_Date -> "Date"
| `JoinForm_Kind_PickOne -> "Choix simple"
| `JoinForm_Kind_PickMany -> "Choix multiple"
| `JoinForm_Kind_Profile -> "Profil"
| `JoinForm_Edit -> "Modifier"
| `JoinForm_Create -> "Ajouter un champ"
| `JoinForm_Create_Cancel -> "Annuler"
| `JoinForm_Create_Submit -> "Enregistrer"
| `JoinForm_Choices -> "Réponses possibles :"
| `JoinForm_Edit_Submit -> "Enregistrer"
| `JoinForm_Edit_Remove -> "Supprimer"
| `JoinForm_Edit_Cancel -> "Annuler"
| `JoinForm_Source_Profile -> "Profil : "
| `JoinForm_Create_Warning -> "Attention : pour le confort des utilisateurs, il est recommandé de garder les formulaires d'inscription aussi courts que possible."
