| `JoinForm_Required -> "Obligatoire"
| `JoinForm_Kind_LongText -> "Texte"
| `JoinForm_Kind_Textarea -> "Texte long"
| `JoinForm_Kind_Date -> "Date"
| `JoinForm_Kind_PickOne -> "Choix simple"
| `JoinForm_Kind_PickMany -> "Choix multiple"
| `JoinForm_Edit -> "Modifier"
| `JoinForm_Create -> "Ajouter un champ"
| `JoinForm_Create_Submit -> "Enregistrer"
| `JoinForm_Choices -> "Réponses possibles :"
