| `Newsletter_Create_Title -> "Composer une Newsletter"
| `Newsletter_Save -> "Enregistrer"
| `Newsletter_Field_Title -> "Titre"
| `Newsletter_Field_Body -> "Contenu"
| `Newsletter_Field_Required -> "Champ obligatoire"
