all: FFBAD FSCF AssoHelp MyInnovation

FFBAD:
	git clone 'git://github.com/RunOrg/PortalFFBAD.git' FFBAD

FSCF:
	git clone 'git://github.com/RunOrg/PortalFSCF.git' FSCF

MyInnovation:
	git clone 'git://github.com/RunOrg/PortalMyInnovation.git' MyInnovation

AssoHelp:
	git clone 'git://github.com/RunOrg/AssoHelp.git' AssoHelp

