all: FFBAD FSCF AssoHelp

FFBAD:
	git clone 'git://github.com/RunOrg/PortalFFBAD.git' FFBAD

FSCF:
	git clone 'git://github.com/RunOrg/PortalFSCF.git' FSCF

AssoHelp:
	git clone 'git://github.com/RunOrg/AssoHelp.git' AssoHelp

