all: FFBAD FSCF AssoHelp MyInnovation M2014

FFBAD:
	git clone 'git://github.com/RunOrg/PortalFFBAD.git' FFBAD

FSCF:
	git clone 'git://github.com/RunOrg/PortalFSCF.git' FSCF

MyInnovation:
	git clone 'git://github.com/RunOrg/PortalMyInnovation.git' MyInnovation

AssoHelp:
	git clone 'git://github.com/RunOrg/AssoHelp.git' AssoHelp

Alfortville:
	git clone 'git://github.com/RunOrg/PortalAlfortville.git' Alfortville

M2014:
	git clone 'git://github.com/RunOrg/PortalM2014.git' M2014