| `Splash_Footer_Actu
| `Splash_Footer_Blog
| `Splash_Footer_Blogs
| `Splash_Footer_Facebook
| `Splash_Footer_Legal
| `Splash_Footer_Login
| `Splash_Footer_Newsletter
| `Splash_Footer_Online
| `Splash_Footer_Tech
| `Splash_Footer_Twitter
| `Splash_Price

| `Splash_Contact_Title 
| `Splash_Contact_Subtitle
| `Splash_Contact_Email 
| `Splash_Contact_Facebook
| `Splash_Contact_Twitter
| `Splash_Contact_Phone
| `Splash_Contact_Phone_Subtitle
| `Splash_Contact_Mail
| `Splash_Contact_Callback
| `Splash_Contact_Callback_Subtitle
| `Splash_Contact_Ok 
| `Splash_Contact_Ok_Subtitle
| `Splash_Contact_Ok_Thanks
| `Splash_Contact_Ok_Sign
| `Splash_Contact_Form_Phone
| `Splash_Contact_Form_Required
| `Splash_Contact_Form_Name
| `Splash_Contact_Form_Organization
| `Splash_Contact_Form_Email 
| `Splash_Contact_Form_Message
| `Splash_Contact_Form_Submit
