| `Splash_Footer_Actu -> "Actualités RunOrg"
| `Splash_Footer_Blog -> "Conseils aux Associations"
| `Splash_Footer_Blogs -> "Nos Blogs :"
| `Splash_Footer_Facebook -> "Facebook"
| `Splash_Footer_Legal -> "Mentions Légales"
| `Splash_Footer_Login -> "Connexion"
| `Splash_Footer_Newsletter -> "Newsletter"
| `Splash_Footer_Online -> "Sur Internet :" 
| `Splash_Footer_Tech -> "Détails Techniques"
| `Splash_Footer_Twitter -> "Twitter" 
| `Splash_Price -> "Tarif"
