| `Splash_Footer_Actu -> "Actualités RunOrg"
| `Splash_Footer_Blog -> "Conseils aux Associations"
| `Splash_Footer_Blogs -> "Nos Blogs :"
| `Splash_Footer_Facebook -> "Facebook"
| `Splash_Footer_Legal -> "Mentions Légales"
| `Splash_Footer_Login -> "Connexion"
| `Splash_Footer_Newsletter -> "Newsletter"
| `Splash_Footer_Online -> "Sur Internet :" 
| `Splash_Footer_Tech -> "Détails Techniques"
| `Splash_Footer_Twitter -> "Twitter" 
| `Splash_Price -> "Tarif"

| `Splash_Contact_Title -> "Contactez-nous !"
| `Splash_Contact_Subtitle -> "Nous sommes impatients de vous entendre."
| `Splash_Contact_Email -> "Par e-mail"
| `Splash_Contact_Facebook -> "Par Facebook"
| `Splash_Contact_Twitter -> "Par Twitter"
| `Splash_Contact_Phone -> "Par téléphone"
| `Splash_Contact_Phone_Subtitle -> "Contact commercial"
| `Splash_Contact_Mail -> "Par courrier"
| `Splash_Contact_Callback -> "On vous rappelle "
| `Splash_Contact_Callback_Subtitle -> "Laissez-nous votre numéro, et nous vous rappelons dès que possible."
| `Splash_Contact_Ok -> "Votre demande a bien été prise en compte."
| `Splash_Contact_Ok_Subtitle -> "Nous allons vous appeler au numéro indiqué dans les 48 heures."
| `Splash_Contact_Ok_Thanks -> "Merci pour votre intérêt, et à bientôt par téléphone."
| `Splash_Contact_Ok_Sign -> "L'Équipe RunOrg"
| `Splash_Contact_Form_Phone -> "Numéro de téléphone" 
| `Splash_Contact_Form_Required -> "obligatoire"
| `Splash_Contact_Form_Name -> "Vos nom et prénom"
| `Splash_Contact_Form_Organization -> "Votre organisation, association ou entreprise"
| `Splash_Contact_Form_Email -> "Votre adresse e-mail"
| `Splash_Contact_Form_Message -> "Un message ?"
| `Splash_Contact_Form_Submit -> "Appelez-moi" 
