| `Network_List_WithTag -> "Associations avec l'étiquette"
| `Network_List_All -> "Toutes les associations du réseau RunOrg"
| `Network_List_Filter -> "Filtrer par étiquette"
| `Network_List_Empty -> "Aucune association avec cette étiquette"
| `Network_Title -> "Le Réseau des Associations - RunOrg"
| `Network_Title_WithTag tag -> tag ^ " - Le Réseau des Associations - RunOrg"
