| `Network_List_All -> "Annuaire des associations"
| `Network_List_Filter -> "Filtrer par étiquette"
| `Network_List_Empty -> "Aucune association trouvée"
| `Network_Title -> "Le Réseau des Associations - RunOrg"
| `Network_Search -> "Chercher"

| `Network_Missing -> "Votre association n'apparaît pas dans la liste ?"
| `Network_Missing_Create -> "Créez gratuitement son espace privé"

| `Network_News_Title -> "Actualités - Le Réseau des Associations - RunOrg"
| `Network_News_Explain -> "Cette page recense les actualités des associations du réseau RunOrg. Vous pouvez vous abonner individuellement aux associations dont les actualités vous intéressent."

| `Network_Unbound -> "Installation en cours"
| `Network_Unbound_Welcome -> "Bienvenue !"
| `Network_Unbound_Soon -> "À cette adresse, vous trouverez bientôt :"
| `Network_Unbound_Teaser_Public -> "Un site web public avec des actualités, un agenda et la possibilité d'adhérer en ligne."
| `Network_Unbound_Teaser_Private -> "Un espace membres privé avec forums de discussions, albums photo, agenda privé et partage de documents."
| `Network_Unbound_Installing -> "L'installation de cet espace n'est pas encore achevée."
| `Network_Unbound_Finish -> "Vous êtes responsable de cet espace ?"
| `Network_Unbound_Finish_Submit -> "Finir l'installation"
