| `MeAccount_Detail_Email -> "Email"
| `MeAccount_Detail_Phone -> "Tél. Fixe"
| `MeAccount_Detail_Cellphone -> "Tél. Portable"
| `MeAccount_Detail_Birthdate g -> macho "Né le" "Née le" g
| `MeAccount_Detail_Address -> "Adresse"
| `MeAccount_Detail_Zipcode -> "Code Postal"
| `MeAccount_Detail_Country -> "Pays"
| `MeAccount_Detail_Gender -> "Sexe"
| `MeAccount_Button_Edit -> "Paramètres"
| `MeAccount_Page_Title -> "Mon Compte"
| `MeAccount_Button_Picture -> "Changer la photo"
| `MeAccount_Explain -> "Ceci est votre profil privé. Vous pouvez choisir de partager tout ou partie de ces informations avec les associations dont vous devenez membre."

| `MeAccount_Instances -> "Mes associations"
| `MeAccount_Instances_More -> "Afficher le reste"

| `MeAccount_Admin_Title -> "Paramètres"
| `MeAccount_Admin_Edit_Link -> "Compléter votre profil"
| `MeAccount_Admin_Edit_Sub  -> "Remplissez les informations de votre compte"
| `MeAccount_Admin_Pass_Link -> "Changer mon mot de passe"
| `MeAccount_Admin_Pass_Sub  -> "Entrez un nouveau mot de passe pour vous connecter"
| `MeAccount_Admin_Privacy_Link -> "Vie Privée"
| `MeAccount_Admin_Privacy_Sub  -> "Définissez quelles informations sont visibles et par qui"
| `MeAccount_Admin_Picture_Link -> "Photo de profil"
| `MeAccount_Admin_Picture_Sub -> "Aidez vos interlocuteurs à mettre un visage sur votre nom"

| `MeAccount_Edit_AboutYou -> "À propos de vous"
| `MeAccount_Edit_Title -> "Profil"
| `MeAccount_Edit_Firstname -> "Prénom"
| `MeAccount_Edit_Lastname -> "Nom"
| `MeAccount_Edit_Contact -> "Informations de contact"
| `MeAccount_Edit_Phone -> "Téléphone fixe"
| `MeAccount_Edit_Cellphone -> "Téléphone portable"
| `MeAccount_Edit_Address -> "Adresse"
| `MeAccount_Edit_City -> "Ville"
| `MeAccount_Edit_Zipcode -> "Code postal"
| `MeAccount_Edit_Country -> "Pays"
| `MeAccount_Edit_Gender -> "Sexe"
| `MeAccount_Edit_Male -> "Homme"
| `MeAccount_Edit_Female -> "Femme"
| `MeAccount_Edit_Birthdate -> "Date de naissance · JJ/MM/AAAA"
| `MeAccount_Edit_DateError -> "Format JJ/MM/AAAA nécessaire"
| `MeAccount_Edit_Required -> "Champ obligatoire"
| `MeAccount_Edit_Submit -> "Enregistrer"

| `MeAccount_Pass_Title -> "Mot de passe"
| `MeAccount_Pass_Password -> "Mot de passe"
| `MeAccount_Pass_Pass2 -> "Mot de passe (vérification)"
| `MeAccount_Pass_Required -> "Champ obligatoire"
| `MeAccount_Pass_Submit -> "Enregistrer"

| `MeAccount_Picture_Title -> "Photo"

| `MeAccount_Privacy_Title -> "Vie Privée"
